Repository NoVariableGlobal/global-engine, pull requests merged in 2020-04, with the labels that each got.

#71 FMOD implementation
  README.md
  bin/Files/gshift.json
  bin/Files/mood.json
  bin/Files/scenes.json
  bin/Files/sounds.json
  bin/Files/test.json
  bin/media/sounds/ahaha.wav
  bin/resources.cfg
  bin/resources_d.cfg
  deps/fmod/fmod64.dll
  deps/fmod/lib/fmod64_vc.lib
  project/one-thousand-years.vcxproj
  project/one-thousand-years.vcxproj.filters
  scripts/build.ps1
  src/Application.cpp
  src/ComponentsManager.cpp
  src/Game.cpp
  src/Loader.cpp
  src/Loader.h
  src/SoundComponent.cpp
  src/SoundComponent.h
  src/SoundContext.cpp
  src/SoundContext.h
  src/SoundListenerComponent.cpp
  src/SoundListenerComponent.h
  src/SoundTestIC.cpp
  src/SoundTestIC.h
Labels: enhancement

#78 fix(AnimationLC): tells if the animation has finished
  bin/Files/test.json
  src/AnimationLC.cpp
  src/AnimationLC.h
Labels: sv: patch, t: fix

#74 feat(Audio): Added volume control
  bin/Files/sounds.json
  bin/Files/test.json
  project/one-thousand-years.vcxproj
  project/one-thousand-years.vcxproj.filters
  src/Loader.cpp
  src/SoundComponent.cpp
  src/SoundContext.cpp
  src/SoundContext.h
  src/SoundTestIC.cpp
  src/SoundTestIC.h
Labels: sv: minor, t: feat

#83 refactor: Cleaned up all of the project's code
  project/one-thousand-years.vcxproj
  project/one-thousand-years.vcxproj.filters
  src/AnimationLC.cpp
  src/AnimationLC.h
  src/Application.cpp
  src/CameraRC.cpp
  src/CameraRC.h
  src/Component.cpp
  src/Component.h
  src/ComponentsManager.cpp
  src/ComponentsManager.h
  src/DebugDrawer.cpp
  src/DebugDrawer.h
  src/Entity.cpp
  src/Entity.h
  src/EventComponent.cpp
  src/EventComponent.h
  src/FactoriesFactory.cpp
  src/FactoriesFactory.h
  src/GUI.cpp
  src/GUI.h
  src/Game.cpp
  src/Game.h
  src/InputComponent.cpp
  src/InputComponent.h
  src/ListenerComponent.cpp
  src/ListenerComponent.h
  src/Loader.cpp
  src/Loader.h
  src/OgreSDLContext.cpp
  src/OgreSDLContext.h
  src/PhysicsComponent.cpp
  src/PhysicsComponent.h
  src/PhysicsContext.cpp
  src/PhysicsContext.h
  src/RTSSDefaultTechniqueListener.cpp
  src/RTSSDefaultTechniqueListener.h
  src/RenderComponent.cpp
  src/RenderComponent.h
  src/RigidbodyPC.cpp
  src/RigidbodyPC.h
  src/Scene.cpp
  src/Scene.h
  src/SleepEC.cpp
  src/SleepEC.h
  src/SoundComponent.cpp
  src/SoundComponent.h
  src/SoundContext.cpp
  src/SoundContext.h
  src/SoundListenerComponent.cpp
  src/SoundTestIC.cpp
  src/SoundTestIC.h
  src/SpotLightRC.cpp
  src/SpotLightRC.h
  src/TransformComponent.cpp
  src/TransformComponent.h
  src/TridimensionalObjectRC.cpp
  src/TridimensionalObjectRC.h
  src/Util.h
  src/checkML.h
Labels: sv: major, t: cleanup

#85 fix: Resolved crashes from both latest refactors
  src/Game.cpp
  src/RigidbodyPC.cpp
Labels: sv: patch, t: fix

#90 fix(build): updated script
  README.md
  scripts/build.ps1
Labels: sv: patch, t: build, t: fix
